spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL} # jdbc:mysql://<rds-host>:3306/fdt_prod?sslMode=REQUIRED&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  level:
    com.finediningtheater: WARN
